In [1]:
from sklearn.linear_model import Lasso, Ridge, ElasticNet
import numpy as np

# 데이터셋 가정
X_train = np.random.random((10, 2))
y_train = np.random.random((10, 1))

# 라쏘, 릿지, 엘라스틱넷 적용 선형 회귀 모형 선언
model_l = Lasso(alpha=0.1)
model_r = Ridge(alpha=0.1)
model_e = ElasticNet(alpha=0.1, l1_ratio=0.5)

# 선언된 모형 학습
model_l.fit(X_train, y_train)
model_r.fit(X_train, y_train)
model_e.fit(X_train, y_train)

from sklearn.metrics import mean_squared_error
# 릿지 모델 예측 값
y_pred_l = model_l.predict(X_train)
print(mean_squared_error(y_pred_l, y_train, squared=False))
# 라쏘 모델 예측 값
y_pred_r = model_r.predict(X_train)
print(mean_squared_error(y_pred_r, y_train, squared=False))
# 엘라스틱넷 모델 예측 값
y_pred_e = model_r.predict(X_train)
print(mean_squared_error(y_pred_e, y_train, squared=False))
# 값의 크기가 작을수록 좋다.

0.28964136366774906
0.2896270823208256
0.2896270823208256


# Logistic Regression

In [2]:
# Step 1 : import packages, functions, and classes
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Step 2 : Get data
x = np.arange(10).reshape(-1, 1)
y= np.array([0, 1, 0, 0, 1, 1, 1, 1, 1, 1])

# Step 3 : Create a model and train it
model = LogisticRegression(solver='liblinear', C=10.0, random_state=0)
model.fit(x, y)

# Step 4 : Evaluate the model
p_pred = model.predict_proba(x)
y_pred = model.predict(x)
score_ = model.score(x, y)
conf_m = confusion_matrix(y, y_pred)
report = classification_report(y, y_pred)

# Step 5 : Print
print(p_pred)
print(y_pred)
print(score_)
print(conf_m)
print(report)

[[0.81999686 0.18000314]
 [0.69272057 0.30727943]
 [0.52732579 0.47267421]
 [0.35570732 0.64429268]
 [0.21458576 0.78541424]
 [0.11910229 0.88089771]
 [0.06271329 0.93728671]
 [0.03205032 0.96794968]
 [0.0161218  0.9838782 ]
 [0.00804372 0.99195628]]
[0 0 0 1 1 1 1 1 1 1]
0.8
[[2 1]
 [1 6]]
              precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.86      0.86      0.86         7

    accuracy                           0.80        10
   macro avg       0.76      0.76      0.76        10
weighted avg       0.80      0.80      0.80        10
