In [2]:
import numpy as np

### Numpy Ndarray

In [2]:
array1 = np.array([1,2,3])
print('array1 type :', type(array1))
# np.array()는 변환을 원하는 객체를 인자로 입력하명 ndarray를 반환
print('array1 array 형태 :', array1.shape, '\n')
# array1의 shape는 (3,) -> 1차원 array의 3개의 데이터를 가지고 있음

array2 = np.array([[1, 2, 3], [2, 3, 4]])
print('array2 type :', type(array2))
print('array2 array 형태 :', array2.shape, '\n')
# array2의 shape는 (2, 3) -> 2차원 array로 2개의 로우와 3개의 컬럼

array3 = np.array([[1,2,3]])
print('array3 type :', type(array3))
print('array3 array 형태 :', array3.shape, '\n')
# array2의 shape는 (1, 3) -> 2차원 array로 1개의 로우와 3개의 컬럼

array1 type : <class 'numpy.ndarray'>
array1 array 형태 : (3,) 

array2 type : <class 'numpy.ndarray'>
array2 array 형태 : (2, 3) 

array3 type : <class 'numpy.ndarray'>
array3 array 형태 : (1, 3) 


In [3]:
print(array1.ndim, array2.ndim, array3.ndim)
print(f'array1 : {array1.ndim}차원 \narray2 : {array2.ndim}차원 \narray3 : {array3.ndim}차원')

1 2 2
array1 : 1차원 
array2 : 2차원 
array3 : 2차원


In [4]:
list1 = {1, 2, 3}
print(list1)
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

{1, 2, 3}
<class 'numpy.ndarray'>
{1, 2, 3} object


In [5]:
# int + string / int + float 리스트 ndarray로 변경해보면?
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)
# 문자열 값으로 변환됨(UNICODE)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)
# float64로 변환됨

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [6]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [7]:
# 특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성하기
# 주로 테스트용 데이터 또는 대규모 데이터 일괄 초기화 때 사용
# arrange() - range()와 유사한 기능
# array를 range()로 표현하는 것

sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [8]:
# 특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성하기
# 주로 테스트용 데이터 또는 대규모 데이터 일괄 초기화 때 사용
# zeros() -> shape만 입력하면 모든 값을 0으로 채운 ndarray 반환
# ones() -> shape값을 입력하면 모든 값을 1로 채운 ndarray 반환
# .dtype 정해주지 않으면 기본적으로 float64로 채움

zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [9]:
# reshape() 메서드는 ndarray를 특정 차원 및 크기로 반환
# 예) 0~9까지의 1차원 ndarray를 2row * 5column과  5row * 2column 형태로 2차원  ndarray로 변환

array1 = np.arange(10)
print('array1 : \n', array1)

array2 = array1.reshape(2, 5)
print('array2 : \n', array2)

array3 = array1.reshape(5, 2)
print('array3 : \n', array3)

# 지정된 사이즈로 변경이 불가능 하면 오류 발생 (개수가 맞아야 함)

array1 : 
 [0 1 2 3 4 5 6 7 8 9]
array2 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [4]:
# reshape(에서 인자를 -1로 적용하면 원래 ndarray와 호환되는 새로운 shape로 변환해줌

array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape :', array2.shape)
array3 = array1.reshape(5, -1)
print('array3 shape :', array3.shape)

# -> array1은 1차원 ndarray로 0~9까지의 데이터
# row -1, column 5 
# -> 5개의 column에 맞는 row를 자동으로 새롭게 생성하여 변환 
# -> 10개의 1차원 데이터와 호환될 수 있는 고정된 5개 column에 맞는 row 개수는 2 
# -> 2 * 5의 2차원 ndarray로 변환
# -> (5, -1) 10갱의 1차원 데이터와 호환되는 고정된 5개의 row에 맞는 column은 5*2의 2차원 ndarray로 변환
# -1을 사용하더라도 호환될 수 없는 형태는 반환할 수 없음

[0 1 2 3 4 5 6 7 8 9]
array2 shape : (2, 5)
array3 shape : (5, 2)


In [5]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d : \n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5 : \n', array5.tolist())
print('array5 shape :', array5.shape)

# 1차원 ndarray를 2차원  ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6 : \n', array6.tolist())
print('array6 shape :', array6.shape)

array3d : 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape : (8, 1)
array6 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape : (8, 1)


In [11]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1 :', array1)
# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value :', value)
print(type(value))

print('맨 뒤의 값 :', array1[-1], '\n맨 뒤에서 두 번째 값 :', array1[-2])

array1 : [1 2 3 4 5 6 7 8 9]
value : 3
<class 'numpy.int64'>
맨 뒤의 값 : 9 
맨 뒤에서 두 번째 값 : 8


In [12]:
# 데이터 값 바꾸기
array1[0] = 9
array1[8] = 0
print('array1 :', array1)

array1 : [9 2 3 4 5 6 7 8 0]


In [14]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row = 0, column = 0) index 가리키는 값 :', array2d[0, 0])
print('(row = 0, column = 1) index 가리키는 값 :', array2d[0, 1])
print('(row = 1, column = 0) index 가리키는 값 :', array2d[1, 0])
print('(row = 1, column = 1) index 가리키는 값 :', array2d[1, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row = 0, column = 0) index 가리키는 값 : 1
(row = 0, column = 1) index 가리키는 값 : 2
(row = 1, column = 0) index 가리키는 값 : 4
(row = 1, column = 1) index 가리키는 값 : 5


In [15]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [16]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[:3]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[1 2 3]
[1 2 3 4 5 6 7 8 9]


In [17]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print('array2d : \n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, :] \n', array2d[:2, :])




array2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, :] 
 [[1 2 3]
 [4 5 6]]


In [22]:
array1d = np.arange(1, 10)
# [] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print(f'array1d > 불린 인덱싱 결과 값 : {array3}')

boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print("불린 인덱스로 필터링 결과 :", array3)

indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print("일반 인덱스로 필터링 결과 :", array4)

array1d > 불린 인덱싱 결과 값 : [6 7 8 9]
불린 인덱스로 필터링 결과 : [6 7 8 9]
일반 인덱스로 필터링 결과 : [6 7 8 9]
